In [1]:
class Cat(): #(object) ending not required
  def __init__(self, name, lastname, age, weight, color): # Constructor: These parameters will be used upon class calling(Except self)
    self.name = name # self refers to global variables that can only be used throughout the class
    self.lastname = lastname
    self.age = age
    self.weight = weight 
    self.color = color
  def Introducecat(self): # self is almost always required for a function in a class, unless you don't want to use any of the global class variables
    print (f" Hello! My name is {self.name} {self.lastname}, and I am {self.age} years old. I am not too haevy, just {self.weight} pound, and my color is {self.color} and I love playing with other cats like you.")

  
  def Introducekittyconcert (self):
    print(f" Hi! Gee. I am {self.name} {self.lastname}. I am older than you, {self.age} years old. and my weight is {self.weight} pound. My color is {self.color}, and like you I enjoy playing with other cats.")

cat1 = Cat("Gee","Po", 2, 3, "Brown") #Creates new cat

cat2 = Cat("Taw","Wee", 3, 4, "Yellow") #Creates cat2

cat1.Introducecat() # Calls Introducecat function of cat1 
cat2.Introducekittyconcert() # Calls Introducekittyconcert function of cat2

 Hello! My name is Gee Po, and I am 2 years old. I am not too haevy, just 3 pound, and my color is Brown and I love playing with other cats like you.
 Hi! Gee. I am Taw Wee. I am older than you, 3 years old. and my weight is 4 pound. My color is Yellow, and like you I enjoy playing with other cats.


In [2]:
class Cat(): #(object) ending not required
  def __init__(self, name, lastname, age, weight, color): # Constructor: These parameters will be used upon class calling(Except self)
    self.name = name # self refers to global variables that can only be used throughout the class
    self.lastname = lastname
    self.age = age
    self.weight = weight 
    self.color = color
  def Introducecat(self): # self is almost always required for a function in a class, unless you don't want to use any of the global class variables
    print (f" Hello! My name is {self.name} {self.lastname}, and I am {self.age} years old. I am not too haevy, just {self.weight} pound, and my color is {self.color} and I love playing with other cats like you.")
    
class Kitty(): #(object) ending not required
  def __init__(self, name, lastname, age, weight, color): # Constructor: These parameters will be used upon class calling(Except self)
    self.name = name # self refers to global variables that can only be used throughout the class
    self.lastname = lastname
    self.age = age
    self.weight = weight 
    self.color = color
  
  def Introducekittyconcert (self):
    print(f" Hi! Gee. I am {self.name} {self.lastname}. I am older than you, {self.age} years old. and my weight is {self.weight} pound. My color is {self.color}, and like you I enjoy playing with other cats.")

cat1 = Cat("Gee","Po", 2, 3, "Brown") #Creates new cat

kitty = Kitty("Taw","Wee", 3, 4, "Yellow") #Creates cat2

cat1.Introducecat() # Calls Introducecat function of cat1 
kitty.Introducekittyconcert() # Calls Introducekittyconcert function of cat2

 Hello! My name is Gee Po, and I am 2 years old. I am not too haevy, just 3 pound, and my color is Brown and I love playing with other cats like you.
 Hi! Gee. I am Taw Wee. I am older than you, 3 years old. and my weight is 4 pound. My color is Yellow, and like you I enjoy playing with other cats.


In [3]:
def createGenerator():
    mylist = [1,2,4,8]
    for i in mylist:
        yield "Meow"*i
        
mygenerator = createGenerator()
print (mygenerator)

for i in mygenerator:
    print (i)
    

<generator object createGenerator at 0x000002AFACA48350>
Meow
MeowMeow
MeowMeowMeowMeow
MeowMeowMeowMeowMeowMeowMeowMeow


In [4]:
import numpy as np 

arr0 = np.random.normal(size = (5,5))

x = np.random.normal(size = (5,5))

if  x.all() > 0.09:
    x = x**2
else:
    x = 42

print (x[3])


[0.25126989 0.75781198 0.00108306 0.00755127 0.46074588]


In [6]:
import numpy as np 

arr0 = np.random.normal(size = (5,5))

print (arr0)

x = np.random.normal(size = (5,5))
print (x)

if  x.all() > 0.09:
    x = x**2
else:
    x = 42

print (x[3])


[[-0.76029266 -1.00200004 -1.08221197 -1.18240973  0.61670569]
 [-0.06625085 -0.67199486 -0.76329061 -0.74340406 -1.30323761]
 [-0.34427863 -1.91450021 -0.14944534 -0.53117914 -1.614814  ]
 [ 0.23973843 -0.24273753  0.93309278 -0.57230526 -0.54153548]
 [ 0.28304034 -0.21606855 -1.17302004  0.05457199 -0.40865754]]
[[ 0.11187902 -0.83385592  0.75909234  0.23595482 -0.89203472]
 [-0.78650368 -0.68690812  1.11988855 -0.1996162   0.28508587]
 [ 0.62773324  0.08936223  0.17690864  1.00448451  0.03516243]
 [-0.25221378  0.3457813   0.46333799 -0.72323966  1.12098039]
 [ 0.06760116 -1.76153179 -0.60267857 -1.5271003  -0.02938464]]
[0.06361179 0.11956471 0.21468209 0.52307561 1.25659703]
