In [1]:
#ex.2.1
class Cat(): #(object) ending not required
  def __init__(self, name, lastname, age, weight, color): # Constructor: These parameters will be used upon class calling(Except self)
    self.name = name # self refers to global variables that can only be used throughout the class
    self.lastname = lastname
    self.age = age
    self.weight = weight 
    self.color = color
  def Introducecat(self): # self is almost always required for a function in a class, unless you don't want to use any of the global class variables
    print (f" Hello! My name is {self.name} {self.lastname}, and I am {self.age} years old. I am not too haevy, just {self.weight} pound, and my color is {self.color} and I love playing with other cats like you.")

  
  def Introducekittyconcert (self):
    print(f" Hi! Gee. I am {self.name} {self.lastname}. I am older than you, {self.age} years old. and my weight is {self.weight} pound. My color is {self.color}, and like you I enjoy playing with other cats.")

cat1 = Cat("Gee","Po", 2, 3, "Brown") #Creates new cat

cat2 = Cat("Taw","Wee", 3, 4, "Yellow") #Creates cat2

cat1.Introducecat() # Calls Introducecat function of cat1 
cat2.Introducekittyconcert() # Calls Introducekittyconcert function of cat2

 Hello! My name is Gee Po, and I am 2 years old. I am not too haevy, just 3 pound, and my color is Brown and I love playing with other cats like you.
 Hi! Gee. I am Taw Wee. I am older than you, 3 years old. and my weight is 4 pound. My color is Yellow, and like you I enjoy playing with other cats.


In [2]:
#ex2.1
class Cat(): #(object) ending not required
  def __init__(self, name, lastname, age, weight, color): # Constructor: These parameters will be used upon class calling(Except self)
    self.name = name # self refers to global variables that can only be used throughout the class
    self.lastname = lastname
    self.age = age
    self.weight = weight 
    self.color = color
  def Introducecat(self): # self is almost always required for a function in a class, unless you don't want to use any of the global class variables
    print (f" Hello! My name is {self.name} {self.lastname}, and I am {self.age} years old. I am not too haevy, just {self.weight} pound, and my color is {self.color} and I love playing with other cats like you.")
    
class Kitty(): #(object) ending not required
  def __init__(self, name, lastname, age, weight, color): # Constructor: These parameters will be used upon class calling(Except self)
    self.name = name # self refers to global variables that can only be used throughout the class
    self.lastname = lastname
    self.age = age
    self.weight = weight 
    self.color = color
  
  def Introducekittyconcert (self):
    print(f" Hi! Gee. I am {self.name} {self.lastname}. I am older than you, {self.age} years old. and my weight is {self.weight} pound. My color is {self.color}, and like you I enjoy playing with other cats.")

cat1 = Cat("Gee","Po", 2, 3, "Brown") #Creates new cat

kitty = Kitty("Taw","Wee", 3, 4, "Yellow") #Creates cat2

cat1.Introducecat() # Calls Introducecat function of cat1 
kitty.Introducekittyconcert() # Calls Introducekittyconcert function of cat2

 Hello! My name is Gee Po, and I am 2 years old. I am not too haevy, just 3 pound, and my color is Brown and I love playing with other cats like you.
 Hi! Gee. I am Taw Wee. I am older than you, 3 years old. and my weight is 4 pound. My color is Yellow, and like you I enjoy playing with other cats.


In [3]:
#ex.2.2
[i**2 for i in range (0,101)]
    

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000]

In [4]:
#ex.2.2
import math 
for x in range(1, 101): 
    if x % 2 == 0:
        print(x)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [5]:
#ex.2.3
def createGenerator():
    mylist = [1,2,4,8]
    for i in mylist:
        yield "Meow"*i
        
mygenerator = createGenerator()
print (mygenerator)

for i in mygenerator:
    print (i)


<generator object createGenerator at 0x00000237941A97B0>
Meow
MeowMeow
MeowMeowMeowMeow
MeowMeowMeowMeowMeowMeowMeowMeow


In [6]:
#ex.2.4
import numpy as np 

arr0 = np.random.normal(size = (5,5))

x = np.random.normal(size = (5,5))

if  x.all() > 0.09:
    x = x**2
else:
    x = 42

print (x[3])

[2.71396522e+00 1.14542529e-03 7.40727870e-01 2.29699186e+00
 5.97839848e-02]


In [7]:
#ex.2.4
import numpy as np 

arr0 = np.random.normal(size = (5,5))

print (arr0)

x = np.random.normal(size = (5,5))
print (x)

if  x.all() > 0.09:
    x = x**2
else:
    x = 42

print (x[3])

[[ 0.25081692  0.89700741  0.31245599 -1.44802573 -2.29993201]
 [-1.76126077  0.1286166  -0.28992418 -0.48810502  0.77288117]
 [ 0.59107299 -0.61342323 -0.44447806 -0.14673328  0.41533207]
 [ 0.25282509 -1.21704077  0.30485114  0.46384696  0.1359154 ]
 [ 0.20516695  1.19624609 -0.70431437 -1.94226991 -2.07819711]]
[[-1.8986884   2.35129317  2.84279889  0.35140815  1.80454431]
 [-0.05342727 -0.37032474 -1.73800225  1.46165352  0.80440151]
 [ 0.99570853 -0.52671625 -1.53140765  0.75171377 -1.11646104]
 [-0.03600162  1.07852042 -0.70434324 -0.38655143 -0.40848921]
 [ 1.73483311  0.43410434  0.49741348 -0.44914456 -0.99826776]]
[0.00129612 1.16320629 0.4960994  0.149422   0.16686343]


In [8]:
#ex.3
from sympy import symbols


x,z, a, b = symbols('x z a b')

f = (4 * a * x**2) + (a) + 3 + z + b**2

derivative_f_x = f.diff(x)
derivative_f_z = f.diff(z)
derivative_f_a = f.diff(a)
derivative_f_b = f.diff(b)

print (derivative_f_x)
print (derivative_f_z)
print (derivative_f_a)
print (derivative_f_b)


8*a*x
1
4*x**2 + 1
2*b
