In [2]:
#ex.2.1
class Cat(): #(object) ending not required
  def __init__(self, name, lastname, age, weight, color): # Constructor: These parameters will be used upon class calling(Except self)
    self.name = name # self refers to global variables that can only be used throughout the class
    self.lastname = lastname
    self.age = age
    self.weight = weight 
    self.color = color
  def Introducecat(self): # self is almost always required for a function in a class, unless you don't want to use any of the global class variables
    print (f" Hello! My name is {self.name} {self.lastname}, and I am {self.age} years old. I am not too haevy, just {self.weight} pound, and my color is {self.color} and I love playing with other cats like you.")

  
  def Introducekittyconcert (self):
    print(f" Hi! Gee. I am {self.name} {self.lastname}. I am older than you, {self.age} years old. and my weight is {self.weight} pound. My color is {self.color}, and like you I enjoy playing with other cats.")

cat1 = Cat("Gee","Po", 2, 3, "Brown") #Creates new cat

cat2 = Cat("Taw","Wee", 3, 4, "Yellow") #Creates cat2

cat1.Introducecat() # Calls Introducecat function of cat1 
cat2.Introducekittyconcert() # Calls Introducekittyconcert function of cat2

 Hello! My name is Gee Po, and I am 2 years old. I am not too haevy, just 3 pound, and my color is Brown and I love playing with other cats like you.
 Hi! Gee. I am Taw Wee. I am older than you, 3 years old. and my weight is 4 pound. My color is Yellow, and like you I enjoy playing with other cats.


In [3]:
#ex2.1
class Cat(): #(object) ending not required
  def __init__(self, name, lastname, age, weight, color): # Constructor: These parameters will be used upon class calling(Except self)
    self.name = name # self refers to global variables that can only be used throughout the class
    self.lastname = lastname
    self.age = age
    self.weight = weight 
    self.color = color
  def Introducecat(self): # self is almost always required for a function in a class, unless you don't want to use any of the global class variables
    print (f" Hello! My name is {self.name} {self.lastname}, and I am {self.age} years old. I am not too haevy, just {self.weight} pound, and my color is {self.color} and I love playing with other cats like you.")
    
class Kitty(): #(object) ending not required
  def __init__(self, name, lastname, age, weight, color): # Constructor: These parameters will be used upon class calling(Except self)
    self.name = name # self refers to global variables that can only be used throughout the class
    self.lastname = lastname
    self.age = age
    self.weight = weight 
    self.color = color
  
  def Introducekittyconcert (self):
    print(f" Hi! Gee. I am {self.name} {self.lastname}. I am older than you, {self.age} years old. and my weight is {self.weight} pound. My color is {self.color}, and like you I enjoy playing with other cats.")

cat1 = Cat("Gee","Po", 2, 3, "Brown") #Creates new cat

kitty = Kitty("Taw","Wee", 3, 4, "Yellow") #Creates cat2

cat1.Introducecat() # Calls Introducecat function of cat1 
kitty.Introducekittyconcert() # Calls Introducekittyconcert function of cat2

 Hello! My name is Gee Po, and I am 2 years old. I am not too haevy, just 3 pound, and my color is Brown and I love playing with other cats like you.
 Hi! Gee. I am Taw Wee. I am older than you, 3 years old. and my weight is 4 pound. My color is Yellow, and like you I enjoy playing with other cats.


In [6]:
#ex.2.2
[i**2 for i in range (0,101)]
    

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000]

In [13]:
#ex.2.2
import math 
for x in range(1, 101): 
    if x % 2 == 0:
        print(x)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [ ]:
#ex.2.3
def createGenerator():
    mylist = [1,2,4,8]
    for i in mylist:
        yield "Meow"*i
        
mygenerator = createGenerator()
print (mygenerator)

for i in mygenerator:
    print (i)


In [14]:
#ex.2.4
import numpy as np 

arr0 = np.random.normal(size = (5,5))

x = np.random.normal(size = (5,5))

if  x.all() > 0.09:
    x = x**2
else:
    x = 42

print (x[3])

[3.25920312e+00 4.20286688e-01 1.99252885e-02 9.83113542e-04
 1.89630856e-02]


In [15]:
#ex.2.4
import numpy as np 

arr0 = np.random.normal(size = (5,5))

print (arr0)

x = np.random.normal(size = (5,5))
print (x)

if  x.all() > 0.09:
    x = x**2
else:
    x = 42

print (x[3])

[[ 1.02541152 -0.3973496   2.04419657 -2.85055212  1.58427109]
 [ 1.44783008  0.10012874 -0.14848862  1.26155731  0.19859627]
 [-1.15447884  0.20041507  1.0651249  -1.73049222  0.14301872]
 [-1.25147242 -1.74414646  1.02904489  1.95937331  0.12248116]
 [-0.67273693 -1.02234505  0.13750836  1.68893268 -0.77812049]]
[[-1.20061941 -0.63853649  0.00980663  0.08063378  1.39281229]
 [ 1.36824022 -0.3889005  -0.2311376  -0.09249042  0.64784919]
 [-0.97504145  0.54299187  0.83703698 -0.88096655 -0.33978525]
 [-0.89177944  1.0780816  -0.81649476 -0.18849389 -0.41569143]
 [ 0.11649832 -1.84966998 -0.08367055 -0.32878941 -1.0605894 ]]
[0.79527056 1.16225993 0.6666637  0.03552995 0.17279937]


In [ ]:
#ex.3